# Generated by Django 5.1.2 on 2025-04-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_product_category_productreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
