# Generated by Django 5.1.2 on 2025-04-14 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_product_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Kerala', ' Kerala'), ('hydrabad', 'hydrabad'), ('karanataka', 'banglaor'), ('Tmail Nadu', 'chennai')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HO', 'LapTop'), ('HS', 'Mobile Phone'), ('HM', 'Tablet'), ('HC', 'Smartwatch'), ('SH', 'Camera'), ('HB', 'ear pods')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(default='pending', max_length=50)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
