# Generated by Django 5.1.2 on 2025-04-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_orderstatus_customer_orderstatus_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='delivery_status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
