# Generated by Django 5.1.2 on 2025-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_orderstatus_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HO', 'MILK'), ('HS', 'Curd'), ('HM', 'Ghee'), ('HC', 'IceBar'), ('SH', 'Kulfi'), ('HB', 'Milk Shake'), ('CH', 'Cheese'), ('PA', 'Paneer'), ('LA', 'lassi')], max_length=2, null=True),
        ),
    ]
